#### 1.Datasets merging

In [47]:
import pandas as pd

RANDO_SEED = 42

In [48]:
GAF_COLUMNS = [
    "DB",
    "DB_Object_ID",
    "DB_Object_Symbol", 
    "Qualifier",
    "GO_ID",
    "DB_Reference",
    "Evidence_Code",
    "With_From",
    "Aspect",
    "DB_Object_Name",
    "DB_Object_Synonym",
    "DB_Object_Type",
    "Taxon",
    "Date",
    "Assigned_By",
    "Annotation_Extension",
    "Gene_Product_Form_ID"
]

datasets = [
    {
        "name": "CANAL",
        "gaf_url": "datasets/CANAL-uniprot.gaf.gz",
        "id_url": "datasets/CANAL-uniprot-id.tsv.gz"
    },
    {
        "name": "CANPC",
        "gaf_url": "datasets/CANPC-uniprot.gaf.gz",
        "id_url": "datasets/CANPC-uniprot-id.tsv.gz"
    },
    {
        "name": "YEAST",
        "gaf_url": "datasets/YEAST-uniprot.gaf.gz",
        "id_url": "datasets/YEAST-uniprot-id.tsv.gz"
    }
]

def load_gaf(url):
    return pd.read_csv(url, sep = '\t', comment="!", names=GAF_COLUMNS, dtype=str) 

def load_ids(url):
    return pd.read_csv(url, sep = '\t') 

gaf_list = []
uniprot_list = []
dfs_to_combine = []

for ds in datasets:
    name = ds["name"]
    gaf_url = ds["gaf_url"]
    id_url = ds["id_url"]
    
    print(f"Loading {name}: {gaf_url}, {id_url}")
    gaf_df=load_gaf(gaf_url)
    gaf_df["TAX_Name"] = name
    display(gaf_df)

    ids_df = load_ids(id_url)
    ids_df["TAX_Name"] = name
    display(ids_df)

    gaf_list.append(gaf_df)
    uniprot_list.append(ids_df)

    # merged_df = pd.merge(ids_df, gaf_df, left_on='Entry', right_on='DB_Object_ID')
    # display(merged_df)

    # merged_df["TAX_Name"] = name
    # dfs_to_combine.append(merged_df)

gaf_df = pd.concat(gaf_list, ignore_index=True)
uniprot_df = pd.concat(uniprot_list, ignore_index=True)

merged_df = pd.merge(uniprot_df, gaf_df, left_on='Entry', right_on='DB_Object_ID')
display(merged_df)

Loading CANAL: datasets/CANAL-uniprot.gaf.gz, datasets/CANAL-uniprot-id.tsv.gz

,DB,DB_Object_ID,DB_Object_Symbol,Qualifier,GO_ID,DB_Reference,Evidence_Code,With_From,Aspect,DB_Object_Name,DB_Object_Synonym,DB_Object_Type,Taxon,Date,Assigned_By,Annotation_Extension,Gene_Product_Form_ID,TAX_Name
0,UniProtKB,A0A1D8PC38,CTA2,enables,GO:0000822,GO_REF:0000033,IBA,PANTHER:PTN000311158|SGD:S000002366,F,Cta2p,CTA2|CAALFM_C100040WA|orf19.13531,protein,taxon:237561,20170228,GO_Central,NaN,UniProtKB:A0A1D8PC38,CANAL
1,UniProtKB,A0A1D8PC38,CTA2,enables,GO:0003674,GO_REF:0000015,ND,NaN,F,Cta2p,CTA2|CAALFM_C100040WA|orf19.13531,protein,taxon:237561,20260128,CGD,NaN,UniProtKB:A0A1D8PC38,CANAL
2,UniProtKB,A0A1D8PC38,CTA2,enables,GO:0005543,GO_REF:0000033,IBA,PANTHER:PTN000311158|SGD:S000002366,F,Cta2p,CTA2|CAALFM_C100040WA|orf19.13531,protein,taxon:237561,20170228,GO_Central,NaN,UniProtKB:A0A1D8PC38,CANAL
3,UniProtKB,A0A1D8PC38,CTA2,enables,GO:0031369,GO_REF:0000033,IBA,PANTHER:PTN000311158|SGD:S000002366,F,Cta2p,CTA2|CAALFM_C100040WA|orf19.13531,protein,taxon:237561,20170228,GO_Central,NaN,UniProtKB:A0A1D8PC38,CANAL
4,UniProtKB,A0A1D8PC38,CTA2,involved_in,GO:0016973,GO_REF:0000033,IBA,PANTHER:PTN000311158|PomBase:SPBC31E1.05|SGD:S...,P,Cta2p,CTA2|CAALFM_C100040WA|orf19.13531,protein,taxon:237561,20220623,GO_Central,NaN,UniProtKB:A0A1D8PC38,CANAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67186,RNAcentral,URS0000B1DEAD_237561,URS0000B1DEAD_237561,located_in,GO:0005730,GO_REF:0000115,IEA,Rfam:RF01207,C,Candida albicans snoRNA C4_01580C_A,NaN,snoRNA,taxon:237561,20260727,RNAcentral,NaN,NaN,CANAL
67187,RNAcentral,URS0000B20334_237561,URS0000B20334_237561,involved_in,GO:0006396,GO_REF:0000115,IEA,Rfam:RF01248,P,Candida albicans snoRNA C1_09560C_A,NaN,snoRNA,taxon:237561,20260727,RNAcentral,NaN,NaN,CANAL
67188,RNAcentral,URS0000B20334_237561,URS0000B20334_237561,located_in,GO:0005730,GO_REF:0000115,IEA,Rfam:RF01248,C,Candida albicans snoRNA C1_09560C_A,NaN,snoRNA,taxon:237561,20260727,RNAcentral,NaN,NaN,CANAL
67189,RNAcentral,URS0000C2FD9C_237561,URS0000C2FD9C_237561,enables,GO:0003735,GO_REF:0000115,IEA,Rfam:RF02543,F,25S ribosomal RNA from Candida albicans SC5314...,NaN,rRNA,taxon:237561,20260727,RNAcentral,NaN,NaN,CANAL
67190,RNAcentral,URS0000C2FD9C_237561,URS0000C2FD9C_237561,located_in,GO:0005840,GO_REF:0000115,IEA,Rfam:RF02543,C,25S ribosomal RNA from Candida albicans SC5314...,NaN,rRNA,taxon:237561,20260727,RNAcentral,NaN,NaN,CANAL

,Entry,Gene Ontology IDs,Sequence,TAX_Name
0,A0A1D8PCL1,GO:0005351; GO:0005886; GO:0008643; GO:0016020...,MSSKIERIFSGPALKINTYLDKLPKIYNVFFIASISTIAGMMFGFD...,CANAL
1,A0A1D8PDI4,GO:0000981; GO:0001216; GO:0005634; GO:0006355...,MSEKIKREKPVKVRKHVSSACLECRRRHFKCDGKQPVCDRCQKSNK...,CANAL
2,A0A1D8PDV7,GO:0000045; GO:0000280; GO:0000329; GO:0000407...,MATLSQPQSALPKTKIATTFGLSKDLKSPISVKVCYLECTRNNVSL...,CANAL
3,A0A1D8PFE5,GO:0000282; GO:0001411; GO:0005621; GO:0005886...,MLVQFQQLLLLLISIIKLCQADDNDNSFFQPVSQPSLNYKDTGNRI...,CANAL
4,A0A1D8PFP2,GO:0000785; GO:0000981; GO:0001216; GO:0005634...,MTPSSTKKIKQRRSTSCTVCRTIKRKCDGNTPCSNCLKRNQECIYP...,CANAL
...,...,...,...,...
1461,P85437,GO:0005576,DINGGGATLPQALXQITGVIT,CANAL
1462,Q59LP6,GO:0016020,MSDLLHKLNFKIADASPEYKQRRKIQMIRFFTASAVTIFASRFAYR...,CANAL
1463,Q59PP0,GO:0005737,MLDELSYKVLTNLETSYERKQPLGSKLIDRYTLTIDQSTVAQQSYF...,CANAL
1464,Q59PT4,NaN,MFQKLIVITFAIALASANIFDFLNNFNTGGRQQQNQGVRTPQEYES...,CANAL
1465,Q5AI58,GO:0005634; GO:0005737,MNQLVKLIHEQPNVENTIPHTLYQASSPKLNLAEEDKFIIYASGDK...,CANAL

Loading CANPC: datasets/CANPC-uniprot.gaf.gz, datasets/CANPC-uniprot-id.tsv.gz

,DB,DB_Object_ID,DB_Object_Symbol,Qualifier,GO_ID,DB_Reference,Evidence_Code,With_From,Aspect,DB_Object_Name,DB_Object_Synonym,DB_Object_Type,Taxon,Date,Assigned_By,Annotation_Extension,Gene_Product_Form_ID,TAX_Name
0,UniProtKB,G8B4P6,CPAR2_600010,enables,GO:0003674,GO_REF:0000015,ND,NaN,F,Uncharacterized protein,CPAR2_600010,protein,taxon:578454,20260128,CGD,NaN,UniProtKB:G8B4P6,CANPC
1,UniProtKB,G8B4P6,CPAR2_600010,involved_in,GO:0008150,GO_REF:0000015,ND,NaN,P,Uncharacterized protein,CPAR2_600010,protein,taxon:578454,20260128,CGD,NaN,UniProtKB:G8B4P6,CANPC
2,UniProtKB,G8B4P6,CPAR2_600010,is_active_in,GO:0005575,GO_REF:0000015,ND,NaN,C,Uncharacterized protein,CPAR2_600010,protein,taxon:578454,20260128,CGD,NaN,UniProtKB:G8B4P6,CANPC
3,UniProtKB,G8B4P7,CPAR2_600020,enables,GO:0000166,GO_REF:0000002,IEA,InterPro:IPR023299,F,P-type Na(+) transporter,CPAR2_600020,protein,taxon:578454,20260727,InterPro,NaN,UniProtKB:G8B4P7,CANPC
4,UniProtKB,G8B4P7,CPAR2_600020,enables,GO:0005524,GO_REF:0000002,IEA,InterPro:IPR001757,F,P-type Na(+) transporter,CPAR2_600020,protein,taxon:578454,20260727,InterPro,NaN,UniProtKB:G8B4P7,CANPC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54137,RNAcentral,URS000044C039_578454,URS000044C039_578454,involved_in,GO:0006412,GO_REF:0000108,IEA,GO:0030533,P,Candida parapsilosis tRNA tV(UAC)2mt,NaN,tRNA,taxon:578454,20260727,GOC,NaN,NaN,CANPC
54138,RNAcentral,URS00004D292C_578454,URS00004D292C_578454,enables,GO:0003735,GO_REF:0000115,IEA,Rfam:RF02543,F,Candida parapsilosis rRNA CPAR2_701540,NaN,rRNA,taxon:578454,20260727,RNAcentral,NaN,NaN,CANPC
54139,RNAcentral,URS00004D292C_578454,URS00004D292C_578454,located_in,GO:0005840,GO_REF:0000115,IEA,Rfam:RF02543,C,Candida parapsilosis rRNA CPAR2_701540,NaN,rRNA,taxon:578454,20260727,RNAcentral,NaN,NaN,CANPC
54140,RNAcentral,URS00005E634E_578454,URS00005E634E_578454,enables,GO:0030533,GO_REF:0000115,IEA,Rfam:RF00005,F,Candida parapsilosis tRNA tL(UAG)1mt,NaN,tRNA,taxon:578454,20260727,RNAcentral,NaN,NaN,CANPC
54141,RNAcentral,URS00005E634E_578454,URS00005E634E_578454,involved_in,GO:0006412,GO_REF:0000108,IEA,GO:0030533,P,Candida parapsilosis tRNA tL(UAG)1mt,NaN,tRNA,taxon:578454,20260727,GOC,NaN,NaN,CANPC

,Entry,Gene Ontology IDs,Sequence,TAX_Name
0,G8BAW7,GO:0000287; GO:0004312; GO:0004315; GO:0004316...,MKPEIEQELSHTLLTELLAYQFASPVRWIETQDVFLKQHNTERVIE...,CANPC
1,G8BHG6,GO:0004090; GO:0005975; GO:0050085; GO:0050664,MGEIESYCNKELGPLPTKAPTLSKNVLDLFSLKGKVASVTGSSGGI...,CANPC
2,Q76L36,GO:0008106; GO:0016652; GO:0036441; GO:0042180...,MTQSNLLPKTFRTKSGKEISIALGTGTKWKQAQTINDVSTELVDNI...,CANPC
3,Q76L37,GO:0016652; GO:0036441; GO:0042180; GO:0047011,MSLAGKEFKLSNGNKIPAVAFGTGTKYFKRGHNDLDKQLIGTLELA...,CANPC
4,G8B839,GO:0000262; GO:0000725; GO:0003690; GO:0003697...,MLHSTKLVFRATPQALCFPVRSYSRYVRTVPKTASAKTTSKLAPSI...,CANPC
5,G8BHG4,GO:0004090; GO:0005975; GO:0050085; GO:0050664,MGEIESYCNKELGPLPTKAPTLSKNVLDLFSLKGKVASVTGSSGGI...,CANPC
6,P32951,GO:0004190; GO:0005576; GO:0006508,MVAIVTLTRQVLLTIALALFAQGAAIPEEAAKRDDNPGFVALDFDV...,CANPC
7,Q6Y0Z3,GO:0032866; GO:0042843,MSTATASPAVKLNSGYEIPLVGFGCWKLTNDVASDQIYRAIKSGYR...,CANPC
8,G8BA04,GO:0005829; GO:0016646,MKVIRDKDIKSFLNKRLTRESIFSQFQPVLLRGLATYAANPNAIVP...,CANPC
9,G8BHG5,GO:0004090; GO:0005975; GO:0050085; GO:0050664,MGEIESYCNKELGPLPTKAPTLAKNVLDLFSLKGKVASVTGSSGGI...,CANPC
10,G8BHG7,GO:0004090; GO:0005975; GO:0050085; GO:0050664,MSKDETISYCNDQLGPLPTTAPKVSDNVTDLFSFKGKVVSVTGSSG...,CANPC
11,O42821,GO:0000411; GO:0004335; GO:0005524; GO:0005829...,MSVPKFNDLSFYSDPSAHKSRYANLVKTFKSKYPNDEIEFFARSPG...,CANPC
12,P32950,GO:0004190; GO:0005576; GO:0006508,MTTIAIFTKNVLLAIAFALFAQGAAIPDPAKRDDNPGFVALDFEVT...,CANPC
13,Q03671,GO:0005743; GO:0045259; GO:0046933,MFYSPLDQFELKPLLLITDNLTFSITNYTLYLIIVSLIIIFYSSII...,CANPC
14,Q2HZ33,GO:0004409; GO:0005759; GO:0009085; GO:0051539,MRLHLHRFISTSTPLRSGQNLTEKIVQKYAVNLPPNKLVHTGDYVT...,CANPC
15,Q34214,GO:0004129; GO:0005743; GO:0006123; GO:0045277...,MTNNVRGYLQLHPFHLVGPSPWPIFTSFSLMDLAFSIALNSHGYMA...,CANPC
16,Q7GEV4,GO:0005743; GO:0006122; GO:0008121; GO:0045275,MPIRKSNTYLSLVNSYLIDSPQPSSINYWWNVGSLLGLCLVIQIAS...,CANPC
17,P17345,GO:0015078; GO:0015986; GO:0031966; GO:0045259,MPQLVPFYFMNLLTGGILAISLLLYFVATYLLPNILRLLIARNIIIKL,CANPC
18,P48909,GO:0008137; GO:0030964; GO:0031966,MFTAYLILCPIIAVVLVGLNWLLATSNSYIEKDGPFECGFTSFQQS...,CANPC
19,P48919,GO:0005743; GO:0008137; GO:0015990; GO:0042773,MFQYLYYIWEEPISISLGNWLNIGDIIIPYGLSLDSLAMTVMIPVG...,CANPC
20,P48923,GO:0008137; GO:0031966,MFLISGISSILAIGLLSPVQSIVCLIVLFVSAAISLYSNGFVLMGI...,CANPC
21,P48929,GO:0008137; GO:0030964; GO:0031966; GO:0042773,MLALISILLLFYISQNNLITLLIAIEILLLTVTVKLIYMGSVYDDI...,CANPC
22,Q12595,GO:0004590; GO:0005829; GO:0006207; GO:0044205,MVTNKSYRERSDTSSSPVTRRLFHLMEQKQSNLCASVDVRTTKELL...,CANPC

Loading YEAST: datasets/YEAST-uniprot.gaf.gz, datasets/YEAST-uniprot-id.tsv.gz

,DB,DB_Object_ID,DB_Object_Symbol,Qualifier,GO_ID,DB_Reference,Evidence_Code,With_From,Aspect,DB_Object_Name,DB_Object_Synonym,DB_Object_Type,Taxon,Date,Assigned_By,Annotation_Extension,Gene_Product_Form_ID,TAX_Name
0,UniProtKB,A0A023PYF4,YER145C-A,enables,GO:0003674,GO_REF:0000015,ND,NaN,F,Uncharacterized protein YER145C-A,YER145C-A,protein,taxon:559292,20150720,SGD,NaN,UniProtKB:A0A023PYF4,YEAST
1,UniProtKB,A0A023PYF4,YER145C-A,involved_in,GO:0008150,GO_REF:0000015,ND,NaN,P,Uncharacterized protein YER145C-A,YER145C-A,protein,taxon:559292,20150720,SGD,NaN,UniProtKB:A0A023PYF4,YEAST
2,UniProtKB,A0A023PYF4,YER145C-A,is_active_in,GO:0005575,GO_REF:0000015,ND,NaN,C,Uncharacterized protein YER145C-A,YER145C-A,protein,taxon:559292,20150720,SGD,NaN,UniProtKB:A0A023PYF4,YEAST
3,UniProtKB,A0A023PZB3,FMP49,enables,GO:0003674,GO_REF:0000015,ND,NaN,F,"Protein FMP49, mitochondrial",FMP49|YER038W-A,protein,taxon:559292,20150720,SGD,NaN,UniProtKB:A0A023PZB3,YEAST
4,UniProtKB,A0A023PZB3,FMP49,involved_in,GO:0008150,GO_REF:0000015,ND,NaN,P,"Protein FMP49, mitochondrial",FMP49|YER038W-A,protein,taxon:559292,20150720,SGD,NaN,UniProtKB:A0A023PZB3,YEAST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137559,RNAcentral,URS00023119EF_559292,URS00023119EF_559292,located_in,GO:0005840,GO_REF:0000115,IEA,Rfam:RF01960,C,18S Ribosomal RNA from Saccharomyces cerevisia...,NaN,rRNA,taxon:559292,20260727,RNAcentral,NaN,NaN,YEAST
137560,RNAcentral,URS0002311A0A_559292,URS0002311A0A_559292,enables,GO:0003735,GO_REF:0000115,IEA,Rfam:RF01960,F,18S Ribosomal RNA from Saccharomyces cerevisia...,NaN,rRNA,taxon:559292,20260727,RNAcentral,NaN,NaN,YEAST
137561,RNAcentral,URS0002311A0A_559292,URS0002311A0A_559292,located_in,GO:0005840,GO_REF:0000115,IEA,Rfam:RF01960,C,18S Ribosomal RNA from Saccharomyces cerevisia...,NaN,rRNA,taxon:559292,20260727,RNAcentral,NaN,NaN,YEAST
137562,RNAcentral,URS0002F12C84_559292,URS0002F12C84_559292,enables,GO:0003735,GO_REF:0000115,IEA,Rfam:RF01960,F,18S Ribosomal RNA from Saccharomyces cerevisia...,NaN,rRNA,taxon:559292,20260727,RNAcentral,NaN,NaN,YEAST
137563,RNAcentral,URS0002F12C84_559292,URS0002F12C84_559292,located_in,GO:0005840,GO_REF:0000115,IEA,Rfam:RF01960,C,18S Ribosomal RNA from Saccharomyces cerevisia...,NaN,rRNA,taxon:559292,20260727,RNAcentral,NaN,NaN,YEAST

,Entry,Gene Ontology IDs,Sequence,TAX_Name
0,A0A0B7P3V8,GO:0003676; GO:0003887; GO:0003964; GO:0004523...,MATPVRDETRNVIDDNISARIQSKVKTNDTVRQTPSSLRKVSIKDE...,YEAST
1,A6ZM04,GO:0000723; GO:0003697; GO:0005524; GO:0005730...,MPKWIRSTLNHIIPRRPFICSFNSFLLLKNVSHAKLSFSMSSRGFR...,YEAST
2,A6ZU07,GO:0000045; GO:0000422; GO:0004674; GO:0005524...,MGDIKNKDHTTSVNHNLMASAGNYTAEKEIGKGSFATVYRGHLTSD...,YEAST
3,A6ZXH8,GO:0000139; GO:0000422; GO:0005776; GO:0005789...,MERDEYQLPNSHGKNTFLSRIFGLQSDEVNPSLNSQEMSNFPLPDI...,YEAST
4,A6ZY89,GO:0003855; GO:0003856; GO:0003866; GO:0004764...,MVQLAKVPILGNDIIHVGYNIHDHLVETIIKHCPSSTYVICNDTNL...,YEAST
...,...,...,...,...
7928,Q9ZZW3,GO:0005739,MGLWISFGTPPSYTYLLIMNHKLLLINNNNLTEVHTYFNININIDK...,YEAST
7929,Q9ZZW4,GO:0005739,MTGSGTPPSREVNTYYMTMTMTMTMIMIMTMTMNIHFNNNNNNNIN...,YEAST
7930,Q9ZZX7,GO:0005739,MLMMYMLFIMMKTYPMLSYHMMSYHIMLYTIMWYMKYSTYMRLWLL...,YEAST
7931,Q9ZZX8,GO:0005739,MCATYMFNITVIITHPTPTLRTRGPGFVRNRDLYIYKYKSNLINNL...,YEAST
7932,Q9ZZX9,GO:0005739,MYYIMFLYNMLLIIILIFYSIVGVPIIIFNNNYYWDPDIFLFIIYY...,YEAST

,Entry,Gene Ontology IDs,Sequence,TAX_Name_x,DB,DB_Object_ID,DB_Object_Symbol,Qualifier,GO_ID,DB_Reference,...,Aspect,DB_Object_Name,DB_Object_Synonym,DB_Object_Type,Taxon,Date,Assigned_By,Annotation_Extension,Gene_Product_Form_ID,TAX_Name_y
0,A0A1D8PCL1,GO:0005351; GO:0005886; GO:0008643; GO:0016020...,MSSKIERIFSGPALKINTYLDKLPKIYNVFFIASISTIAGMMFGFD...,CANAL,UniProtKB,A0A1D8PCL1,HGT1,enables,GO:0005351,GO_REF:0000033,...,F,High-affinity glucose transporter 1,HGT1|HGT11|CAALFM_C101980WA|orf19.4527,protein,taxon:237561,20220926,GO_Central,NaN,UniProtKB:A0A1D8PCL1,CANAL
1,A0A1D8PCL1,GO:0005351; GO:0005886; GO:0008643; GO:0016020...,MSSKIERIFSGPALKINTYLDKLPKIYNVFFIASISTIAGMMFGFD...,CANAL,UniProtKB,A0A1D8PCL1,HGT1,enables,GO:0022857,GO_REF:0000002,...,F,High-affinity glucose transporter 1,HGT1|HGT11|CAALFM_C101980WA|orf19.4527,protein,taxon:237561,20260727,InterPro,NaN,UniProtKB:A0A1D8PCL1,CANAL
2,A0A1D8PCL1,GO:0005351; GO:0005886; GO:0008643; GO:0016020...,MSSKIERIFSGPALKINTYLDKLPKIYNVFFIASISTIAGMMFGFD...,CANAL,UniProtKB,A0A1D8PCL1,HGT1,enables,GO:0055056,PMID:10612724,...,F,High-affinity glucose transporter 1,HGT1|HGT11|CAALFM_C101980WA|orf19.4527,protein,taxon:237561,20140625,CGD,NaN,UniProtKB:A0A1D8PCL1,CANAL
3,A0A1D8PCL1,GO:0005351; GO:0005886; GO:0008643; GO:0016020...,MSSKIERIFSGPALKINTYLDKLPKIYNVFFIASISTIAGMMFGFD...,CANAL,UniProtKB,A0A1D8PCL1,HGT1,involved_in,GO:0008643,GO_REF:0000033,...,P,High-affinity glucose transporter 1,HGT1|HGT11|CAALFM_C101980WA|orf19.4527,protein,taxon:237561,20260601,GO_Central,NaN,UniProtKB:A0A1D8PCL1,CANAL
4,A0A1D8PCL1,GO:0005351; GO:0005886; GO:0008643; GO:0016020...,MSSKIERIFSGPALKINTYLDKLPKIYNVFFIASISTIAGMMFGFD...,CANAL,UniProtKB,A0A1D8PCL1,HGT1,involved_in,GO:0030447,PMID:21844307,...,P,High-affinity glucose transporter 1,HGT1|HGT11|CAALFM_C101980WA|orf19.4527,protein,taxon:237561,20140625,CGD,NaN,UniProtKB:A0A1D8PCL1,CANAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153428,Q9ZZX8,GO:0005739,MCATYMFNITVIITHPTPTLRTRGPGFVRNRDLYIYKYKSNLINNL...,YEAST,UniProtKB,Q9ZZX8,Q0017,located_in,GO:0005739,GO_REF:0000044,...,C,"Putative uncharacterized protein Q0017, mitoch...",Q0017|ORF7,protein,taxon:559292,20260727,UniProt,NaN,UniProtKB:Q9ZZX8,YEAST
153429,Q9ZZX9,GO:0005739,MYYIMFLYNMLLIIILIFYSIVGVPIIIFNNNYYWDPDIFLFIIYY...,YEAST,UniProtKB,Q9ZZX9,Q0010,enables,GO:0003674,GO_REF:0000015,...,F,"Putative uncharacterized protein Q0010, mitoch...",Q0010|ORF6,protein,taxon:559292,20130808,SGD,NaN,UniProtKB:Q9ZZX9,YEAST
153430,Q9ZZX9,GO:0005739,MYYIMFLYNMLLIIILIFYSIVGVPIIIFNNNYYWDPDIFLFIIYY...,YEAST,UniProtKB,Q9ZZX9,Q0010,involved_in,GO:0008150,GO_REF:0000015,...,P,"Putative uncharacterized protein Q0010, mitoch...",Q0010|ORF6,protein,taxon:559292,20130808,SGD,NaN,UniProtKB:Q9ZZX9,YEAST
153431,Q9ZZX9,GO:0005739,MYYIMFLYNMLLIIILIFYSIVGVPIIIFNNNYYWDPDIFLFIIYY...,YEAST,UniProtKB,Q9ZZX9,Q0010,is_active_in,GO:0005575,GO_REF:0000015,...,C,"Putative uncharacterized protein Q0010, mitoch...",Q0010|ORF6,protein,taxon:559292,20210730,SGD,NaN,UniProtKB:Q9ZZX9,YEAST
153432,Q9ZZX9,GO:0005739,MYYIMFLYNMLLIIILIFYSIVGVPIIIFNNNYYWDPDIFLFIIYY...,YEAST,UniProtKB,Q9ZZX9,Q0010,located_in,GO:0005739,GO_REF:0000044,...,C,"Putative uncharacterized protein Q0010, mitoch...",Q0010|ORF6,protein,taxon:559292,20260727,UniProt,NaN,UniProtKB:Q9ZZX9,YEAST

In [49]:
HIGH_QUALITY_EC = ['EXP', 'IDA', 'IPI', 'IMP', 'IGI', 'IEP', 'HTP', 'HDA', 'HMP', 'HGI', 'HEP', 'TAS', 'IC']

genes_df = genes_df.loc[genes_df['Evidence_Code'].isin(HIGH_QUALITY_EC)]

genes_df.describe()

,Entry,Gene Ontology IDs,Sequence,DB,DB_Object_ID,DB_Object_Symbol,Qualifier,GO_ID,DB_Reference,Evidence_Code,...,Aspect,DB_Object_Name,DB_Object_Synonym,DB_Object_Type,Taxon,Date,Assigned_By,Annotation_Extension,Gene_Product_Form_ID,TAX_Name
count,82762,82745,82762,82762,82762,82762,82762,82762,82762,82762,...,82762,82762,82737,82762,82762,82762,82762,6780,82762,82762
unique,6198,5714,6164,1,6198,5773,14,5276,14538,11,...,3,5869,6197,1,3,2487,20,1966,6213,3
top,P39940,GO:0002181; GO:0003735; GO:0005737; GO:0005829...,MPSSISVKLVAAESLYKRDVFRSPDPFAVLTIDGYQTKSTSAAKKT...,UniProtKB,P39940,RSP5,enables,GO:0005515,PMID:37968396,IPI,...,F,E3 ubiquitin-protein ligase RSP5,RSP5|MDP1|NPI1|YER125W|SYGP-ORF41,protein,taxon:559292,20130807,SGD,occurs_in(GO:0030529),UniProtKB:P39940,YEAST
freq,176,272,176,82762,176,176,31605,20623,3655,25122,...,32514,176,176,82762,77873,24210,47054,310,176,77873

In [ ]:
gaf_grouped = (
    genes_df.groupby("DB_Object_ID")["GO_ID"]
    .apply(lambda s: set(s.dropna()))
    .rename("go_gaf")
)

def parse_go(x):
    if pd.isna(x) or not str(x).strip():
        return set()
    return set(term.strip() for term in str(x).split(";") if term.strip())

uniprot_df["go_uniprot"] = uniprot_df["Gene Ontology IDs"].apply(parse_go)

comparison = uniprot_df.set_index("Entry")[["go_uniprot"]].join(gaf_grouped, how="left")

comparison["is_identical"] = comparison["go_uniprot"] == comparison["go_gaf"]
comparison["diff_gt_minus_gaf"] = comparison["go_uniprot"] - comparison["go_gaf"]
comparison["diff_gaf_minus_gt"] = comparison["go_gaf"] - comparison["go_uniprot"]

total = len(comparison)
ident = comparison["is_identical"].sum()
diffs = total - ident

print(f"Total proteins number {total}")
print(f"Identical {ident} ({(ident/total)*100:.2f}%)")
print(f"Differing: {diffs} ({(diffs/total)*100:.2f}%)")

Total proteins number 9422
Identical 803 (8.52%)
Differing: 8619 (91.48%)